### ISSUE TITLE
invisible recaptcha

### ISSUE THREAD

**Issue by misaon** [uestla/ReCaptchaControl#13]
Hi! Thanks a lot, this is very helpful library. I have question. I need implement invisible recaptcha from Google. Can i do this with your library? ty 😄

**Comment by uestla** [comment]
What is this? Some kind of black magic?

**Comment by misaon** [comment]
Not, its Google magic https://www.google.com/recaptcha/intro/comingsoon/invisible.html

**Comment by uestla** [comment]
Oh, I've about this few years ago but had no idea it is available now :-)

I'll check it out in some spare time if I found any (maybe someone will come with PR inbetween :-) ).

**Comment by michallohnisky** [comment]
+1

**Comment by uestla** [comment]
@misaon @michallohnisky Guys, I don't have much time for this :-(

Can you please send here your code which isn't working? It could be a good thing to start with, thanks.

**Comment by uestla** [comment]
@misaon I just added the invisible reCAPTCHA on [demo page](https://kesspess.cz/recaptcha/invisible).

The code itself can be seen in [tests/manual](tests/manual) directory:

- form definitions in [TestPresenter](blob/b238cd3c6e3e41fbca2def6ac93e544c482af482/tests/manual/app/presenters/TestPresenter.php#L87-L92)
- template in [invisible.latte](blob/b238cd3c6e3e41fbca2def6ac93e544c482af482/tests/manual/app/presenters/templates/Test/invisible.latte)

Would you please take a time and look if that code is working for you?

**Comment by uestla** [comment]
ping @misaon @michallohnisky

**Comment by uestla** [comment]
ping @misaon @michallohnisky No. 2 :-)

**Comment by michallohnisky** [comment]
We put it into out project and it seems to work nicely. Thank you :-).

**Comment by uestla** [comment]
Closing (considering it to be working).
