### ISSUE TITLE
Class Nette\Utils\ObjectMixin is deprecated

### ISSUE THREAD

**Issue by romancampula** [uestla/ReCaptchaControl#16]
Hello,
after updating Nette to the newest version (2018-02-18) ReCaptchaControl cannot be loaded.

Nette error: Class Nette\Utils\ObjectMixin is deprecated

**Comment by uestla** [comment]
Hi, I tried to reproduce it:

- installed latest `nette/web-project` (v1.8.11)
- added `uestla/recaptcha-control` (version `6.0.0`)
- created simple form with recaptcha
- rendered that form in template

Everything is working with no deprecation error.

**Comment by uestla** [comment]
@romancampula Maybe related to https://forum.nette.org/cs/29189-jak-na-extension-methods-ve-formularich#p195375 ?

**Comment by romancampula** [comment]
Maybe. We will see after Nette update in few days.

**Comment by uestla** [comment]
@romancampula Could you please test it after [today's fix](https://forum.nette.org/en/30125-nette-framework-2-4-2018-02-06#p195380)?

**Comment by romancampula** [comment]
Now it works! Sorry I marked this software as problematic. The problem was on the Nette side.
