### ISSUE TITLE
Verification does not work

### ISSUE THREAD

**Issue by ondrejsabrnak** [uestla/ReCaptchaControl#17]
I added reCaptchaControl on my web www.ondrej.sabrnak.cz. reCaptcha is displayed as it should but verification does not work. The form can proceed without checking I am not a robot.

**Comment by uestla** [comment]
I'll need more info:

- version of `ReCaptchaControl`?
- "form can proceed" means it fires `onSuccess` event?

**Comment by ondrejsabrnak** [comment]
- I used composer so it should be the newest version of ReCaptchaControl.
- Yes it fires onSuccess event
- $form->addReCaptcha(
            'captcha', // control name
            'reCAPTCHA for you', // label
            "Please prove you're not a robot." // error message
        );
- <div class="form-group row">
       <label n:name=captcha class="col-sm-2 col-form-label">reCAPTCHA:</label>
       <div class="col">
           {input captcha}
       </div>
  </div>

**Comment by uestla** [comment]
Please run `composer info` to see the particular version.

Can you create an isolated example to reproduce this please?

**Comment by ondrejsabrnak** [comment]
version: **7.0.0**

I created contact form only on page http://ondrej.sabrnak.cz

**Comment by ondrejsabrnak** [comment]
I fixed the nested forms issue.

Sorry I am new at nette framework so i posted my contact project on github.
https://github.com/ondrejsabrnak/contact-form

**Comment by uestla** [comment]
That's OK.

You don't render errors - please add [this line](https://github.com/uestla/ReCaptchaControl/blob/c8faff735549c380c2d5f527f02c9b171d4b2b48/tests/manual/app/presenters/templates/%40form.latte#L27) after your `{input captcha}` [here](https://github.com/ondrejsabrnak/contact-form/blob/521fcf7a8caf75ba1378cc2ae34f7e955890aac7/app/presenters/templates/Homepage/default.latte#L38)

This is quite often the problem - and I've checked I don't mention errors rendering in the readme file, so I'll better add it ASAP :-)

**Comment by ondrejsabrnak** [comment]
It returns error:
![screenshot_1](https://user-images.githubusercontent.com/37846513/40279480-91689654-5c43-11e8-9fb8-6cbae32816f4.png)

**Comment by uestla** [comment]
Sorry - I didn't mean to directly Copy-Paste the line, but use the logic of it.

I guest you'll need something like

```latte
<span class="help-block" n:ifcontent>{$form['recaptcha']->error ?: $form['recaptcha']->getOption(description)}</span>
```

**Comment by ondrejsabrnak** [comment]
Thanks, now it shows the error message. But it show error message also when i check that I am not a robot :D I wonder if a shouldnt add the **URL** (https://www.google.com/recaptcha/api/siteverify) and **response** (g-recaptcha-response) somewhere

**Comment by ondrejsabrnak** [comment]
Hmm thats weird. I tried it on localhost and it works. But when i use recaptcha online it doesnt work :D

**Comment by uestla** [comment]
Do you have cURL extension enabled in production?

**Comment by ondrejsabrnak** [comment]
I followed the installation instructions so i have this code in my config.neon
```
recaptcha:
	# required
	siteKey: 'mySiteKey'
	secretKey: 'mySecretKey'

	# optional
	methodName: 'addReCaptcha'
	requester: ReCaptchaControl\Http\Requester\CurlRequester
```

**Comment by uestla** [comment]
I know, but do you have `php_curl` extension activated on production?

**Comment by ondrejsabrnak** [comment]
How do i do that ?

**Comment by uestla** [comment]
http://lmgtfy.com/?q=php+is+curl+enabled%3F ;-)

**Comment by ondrejsabrnak** [comment]
cURL is installed

**Comment by uestla** [comment]
OK, then we'll just have to dig deep into the code I guess...

Could you dump the `$errno` variable after [this line](https://github.com/uestla/ReCaptchaControl/blob/c8faff735549c380c2d5f527f02c9b171d4b2b48/src/ReCaptchaControl/Http/Requester/CurlRequester.php#L50) and see what's in it please?

**Comment by ondrejsabrnak** [comment]
It did nothing

**Comment by uestla** [comment]
Did you `exit();` the script after dumping the variable?

**Comment by ondrejsabrnak** [comment]
Yes I did

**Comment by uestla** [comment]
> It did nothing

Does it mean nothing has been rendered or the script continued as before? How are you dumping the variable?

**Comment by uestla** [comment]
ping @ondrejsabrnak

**Comment by uestla** [comment]
That was my suggestion, but if you have cURL enabled, `CurlRequester` configured and it still didn't dump the variable, something strange is happening.

**Comment by uestla** [comment]
@ondrejsabrnak Have you made any progress with the webhoster?

**Comment by uestla** [comment]
ping @ondrejsabrnak

**Comment by uestla** [comment]
Inactive - closing.
