### ISSUE TITLE
Compatibility Nette Forms 3.0.1

### ISSUE THREAD

**Issue by spernica** [uestla/ReCaptchaControl#23]
Declaration of ReCaptchaControl\Control::isFilled() must be compatible with Nette\Forms\Controls\BaseControl::isFilled(): bool

```
// before
public function isFilled()
{
	return true;
}

// now must be
public function isFilled(): bool
{
	return true;
}
```

**Comment by uestla** [comment]
See https://github.com/uestla/ReCaptchaControl/commit/a0c49d3f083b27db52397f384e36a38b13059995#diff-60f28a01ae95b3bc0eb50a8335131a8aR63

Try upgrading to 8.0

**Comment by spernica** [comment]
Sorry, I was on 7.0.1 version and didn't catch new version
