### ISSUE TITLE
Ajax request

### ISSUE THREAD

**Issue by miloshavlicek** [uestla/ReCaptchaControl#6]
After submitting form with confirmed reCaptcha via ajax request, I have issues with js.... Log from my console is: "Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "http://localhost".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match." On my production server (https) it is the same, but there is at the end is "... protocols, domains, and ports must match.". I've tried to set Access-Control-Allow-Origin: * ... but without success.

**Comment by uestla** [comment]
Have you set proper domain in your reCAPTCHA settings?

**Comment by uestla** [comment]
Inactive, closing...
