### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by Trsak** [uestla/ReCaptchaControl#7]
Fatal Error
Maximum function nesting level of '100' reached, aborting!

**Comment by uestla** [comment]
Thanks for the report.

Unfortunately, I have no idea how did you get this error or how should I reproduce it :-(

**Comment by Trsak** [comment]
Vyřešeno.
http://forum.nette.org/cs/24036-maximum-function-nesting-level-of-100-reached-aborting#p161252

**Comment by uestla** [comment]
Thanks.
